export { default as Clientes } from './Clientes'
export { Dashboard } from './DashBoard'
export { EditServicio } from './EditServicio'
export { default as Liqui } from './Liqui'
export { default as NuevoCliente } from './NuevoCliente'
export { Operarios } from './Operarios'
export { default as Servicios } from './Servicios'
export { default as Sueldos } from './sueldos'
export { default as EditPrecio } from './EditPrecio'
