export { default as Clientes } from './Clientes'
export { default as DashBoard } from './DashBoard'
export { default as EditPrecio } from './EditPrecio'
export { default as EditServicio } from './EditServicio'
export { default as Liqui } from './Liqui'
export { default as NuevoCliente } from './NuevoCliente'
export { default as Operarios } from './Operarios'
export { default as Servicios } from './Servicios'
export * from './index'
export { default as sueldos } from './sueldos'
