export { default as operativos } from './Operativos'
export { default as autos } from './autos'
export { default as camiones } from './camiones'
export * from './index'
export { default as motos } from './motos'
