export { default as Controles } from './Controles'
export { default as data } from './data'
export { default as diario } from './diario'
export * from './index'
export { default as paseo } from './paseo'
