import { Inter } from 'next/font/google'
import './globals.css'
import { Header, Toaster } from '@/components'
import AuthContext from '@/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TransitoVL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Header />
          {children}
          <Toaster />
        </AuthContext>
      </body>
    </html>
  )
}
