import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components'
import { Toaster } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TransitoVL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
        <Toaster />
      </body>
    </html>
  )
}
