import { Inter } from 'next/font/google'
import './globals.css'
import { Header, Toaster } from '@/components'
import getCurrentUser from './actions/getUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TransitoVL',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        {session?.legajo && <Header />}

        {children}
        <Toaster />
      </body>
    </html>
  )
}
