export * from './control'
export { default as home } from './home'
export * from './index'
export { default as login } from './login'
export * from './operativos'
export { default as register } from './register'
export * from './sueldos'
export * from './waze'
